[tool.poetry]
name = "luci"
version = "2.0.2"
description = "üì¶Ô∏è LuCI - Luanti Commandline Interface"
authors = ["Christian Decker <christian.decker@lookslikematrix.de>"]
license = "LGPL"
readme = "README.md"

[tool.poetry.scripts]
luci = "luci.__main__:cli"

[tool.poetry.dependencies]
python = "^3.13"
miney = "^0.5.8"
numpy = "^2.2.0"
trimesh = {extras = ["easy"], version = "^4.10.0"}
click = "^8.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
